---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ndrake-blue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: signing
  
  - type: rpm-ostree
    install:
      - kmodtool
      - akmods
      - dkms
      - kernel-devel
