---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ndrake-blue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: signing
  
  - type: rpm-ostree
    install:
      - kmodtool
      - akmods
      - dkms
      - kernel-devel

  - type: script
    script: |
      #!/bin/bash
      set -exo pipefail
      
      # Download rtl88xxau source
      cd /tmp
      git clone https://github.com/aircrack-ng/rtl8812au.git rtl88xxau
      cd rtl88xxau
      
      # Get current kernel version that's actually in use
      KERNEL_VERSION=$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}' kernel)
      echo "Building for kernel version: $KERNEL_VERSION"
      
      # Build and install the module for current kernel
      make
      make install
      
      # Create kmod package
      cd /usr/lib/modules/$(uname -r)/extra/
      modinfo rtl88xxau || echo "Module not found"
